# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b003f79eade0e257e30e8c8294c656aaad198f8281ea53029e551a82fbd3a8bae2c5172656653fe2649918c6ac14c5764515ba368639d17da5d092cfb48dbf2

test:
  secret_key_base: 22fcb9b7975410bd82092a91e6b238a36e1df4eff67d74dcf18aa3b4926e7772fa506a9f8dd63fa1ffeeffeb6048c684b5503b54edf79bcacd66779c41eed010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
